-- AlterTable
ALTER TABLE "Quote" ADD COLUMN     "autoExpire" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "closingPotential" DECIMAL(5,2),
ADD COLUMN     "companyName" TEXT,
ADD COLUMN     "customerNote" TEXT,
ADD COLUMN     "customerPoDate" TIMESTAMP(3),
ADD COLUMN     "customerPoNumber" TEXT,
ADD COLUMN     "description" TEXT,
ADD COLUMN     "downpaymentPercent" DECIMAL(5,2),
ADD COLUMN     "dueDate" TIMESTAMP(3),
ADD COLUMN     "expiryDate" TIMESTAMP(3),
ADD COLUMN     "inHandDate" TIMESTAMP(3),
ADD COLUMN     "lastEmailedDate" TIMESTAMP(3),
ADD COLUMN     "lastNote" TEXT,
ADD COLUMN     "nextContactDate" TIMESTAMP(3),
ADD COLUMN     "potentialClosingDate" TIMESTAMP(3),
ADD COLUMN     "primaryContactEmail" TEXT,
ADD COLUMN     "primaryContactName" TEXT,
ADD COLUMN     "primaryContactPhoneWithExt" TEXT,
ADD COLUMN     "primarySalesRepName" TEXT,
ADD COLUMN     "quickQuote" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "quoteFor" TEXT,
ADD COLUMN     "shippingDate" TIMESTAMP(3),
ADD COLUMN     "shippingTracking" TEXT,
ADD COLUMN     "site" TEXT,
ADD COLUMN     "title" TEXT,
ADD COLUMN     "totalPriceInDollars" DECIMAL(12,2),
ADD COLUMN     "totalPriceWithTaxInDollars" DECIMAL(12,2),
ADD COLUMN     "totalTaxInDollars" DECIMAL(12,2),
ADD COLUMN     "txnDate" TIMESTAMP(3),
ADD COLUMN     "txnNumber" TEXT,
ADD COLUMN     "workflowState" TEXT DEFAULT 'draft';

-- AlterTable
ALTER TABLE "QuoteLine" ADD COLUMN     "costInDollars" DECIMAL(12,2),
ADD COLUMN     "fullDescription" TEXT,
ADD COLUMN     "name" TEXT,
ADD COLUMN     "priceOverride" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "saleType" TEXT,
ADD COLUMN     "suggestedPriceInDollars" DECIMAL(12,2),
ADD COLUMN     "taxName" TEXT,
ADD COLUMN     "taxRate" DECIMAL(6,4),
ADD COLUMN     "taxable" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "totalCostInDollars" DECIMAL(12,2),
ADD COLUMN     "totalPriceInDollars" DECIMAL(12,2),
ADD COLUMN     "totalTaxInDollars" DECIMAL(12,2),
ADD COLUMN     "uom" TEXT,
ADD COLUMN     "workflowState" TEXT;
